cruise-automation/rosbag.js

lib/MessageReader.js
test/MessageReader.js

Previously, when reading a typed array, we would not advance the offset of the reader, causing subsequent values to be filled incorrectly. This advances the offset so that this no longer happens.

Increment reader offset after reading arrays

---

.eslintrc.yml
lib/BagReader.js
lib/bag.js
package.json
test/Reader.js
test/browser-reader.js
yarn.lock

Bluebird was only used for `promisifyAll` on the bag reader to easily add promise versions of a few internal methods.  Bluebird increases the bundle size of rosbag when used in the browser substantially, so I opted to remove it as a dependency and hand-roll the few places where promise versions of functions are called.

Remove bluebird

---

README.md
lib/BagReader.js
test/rosbag.js

In some decompression scenarios its helpful to know the expected decompressed size of the buffer.  This data is available in the chunk, and this PR adds it to the decompress callback.

Add size to decompress callback

---

lib/readers/node.js

This more than doubles the reading speed in node.js.  A large majority of the work being done during read operations was running gc on the large file read buffers after they have been read.  I also updated to use `Buffer.alloc` instead of `new Buffer` as the later is deprecated in `node@10.x`.

Avoid allocating a new buffer for every file read.

---

lib/MessageReader.js
test/MessageReader.js

So that the user of the `getTypes` function doesn’t have to worry about
those. See http://wiki.ros.org/msg
Test plan: added unit test; manually tested in actual application.

Normalize type aliases

---

lib/MessageReader.js
lib/index.js
lib/parseMessageDefinition.js
test/MessageReader.js
test/parseMessageDefinition.js

Reading a message definition and building a de-serializer are two
separate steps. Splitting the definition parsing from de-serialization
decouples the two and allows for refactoring each while still
maintaining interface boundaries.
---
This PR removes the _customParsers_ feature which is not document and partially functioning.

split message definition parsing out from MessageReader

---

lib/MessageReader.js
lib/MessageReader.test.js

Otherwise you get a whole bunch of undefined keys for constants, which
is not great when printing an entire message, e.g. for debugging.
Test plan: manual; added unit test.

Don’t return constants on messages

---

lib/MessageReader.test.js
lib/Time.test.js
lib/bag.test.js
lib/parseMessageDefinition.test.js
lib/readers/browser.test.js
package.json
yarn.lock

I just followed the guide on https://jestjs.io/docs/en/migration-guide; namely by running `jest-codemods`. No further changes were required.
Changed package.json so that `yarn test` doesn't run an extra copy of the tests when you've run `yarn build` first to produce the `es5` directory.
Motivation: less complexity; jest has some nice helpers like `toMatchObject`.
Test plan: is tests :)

convert tests from chai to jest assertions

---

src/BagReader.js
src/bag.test.js
src/web/index.js
src/web/index.test.js

You cannot read multiple times from the same file reader at once; however, there is nothing in the spec disallowing multiple separate FileReaders from reading from the same file at the same time.
This makes it possible to read several separate chunks or ranges from a bag simultaneously in the browser.
Test plan: Updated tests.  Tested in browser.

Allow multiple reads in browser

---

webpack.config.js

When trying to use this in a webworker I was receiving the error `window is not defined.` Using [this approach](https://github.com/webpack/webpack/issues/6525#issuecomment-417580843) to set the global object.  I tested this in the browser main thread, worker, and in node & everything is working now.
Will need to release a new patch version for this.

Set global object in worker

---

src/TimeUtil.js
src/TimeUtil.test.js

Previously calling `TimeUtil.add` with negative values in either `sec` or `nsec` resulted in undefined-like behavior, producing invalid, negative values in the result without taking into consideration rounding of nsecs to secs.  This change allows for adding a negative time (duration) value to an existing time to produce a new adjusted time with the negative values properly subtracted.  If the resulting time ends up in a negative value, we now throw an exception instead of returning an invalid time value.
Test plan: updated unit tests
Semver impact: this requires a *patch* version bump; we're fixing previously broken behavior.  No new APIs are being added and no existing APIs are being removed.

Improve TimeUtil.add

---

src/bag.js

These instance variable Flowtypes are a bit funky anyway, since they're
only present after calling `Bag#open()`, not on construction, but I think
for our purposes that's generally okay. But startTime/endTime can not
get set at all even after calling `Bag#open()`, i.e. when chunkCount is
zero.

Fix Bag#startTime/endTime not always being present

---

src/BagReader.js
src/index.js
src/node/index.js
src/types.js
src/web/index.js

These are useful when passing your own `Filelike` into a `BagReader`.
Test plan: tried it out with an actual script that uses these types.

Export `Filelike` and `Callback` types

---

package.json
yarn.lock

I happened to be using Windows to build a local version of the library so this PR makes two changes to support that:
- Add [cross-env](http://npmjs.com/package/cross-env) package to support environment variables on Windows.
- Remove the slash after "dist" in `mkdir -p dist/` because it was causing the command to fail.
I haven't tested this on a unix machine but I believe these changes should be cross compatible and if not would think the CI would fail.
Thanks!

Use cross-env package to support building on Windows

---

package.json
src/BagReader.js
yarn.lock

**SUMMARY:**
- Earlier version of `int53` package merely invoked `console.assert()` for certain errors, instead of actually throwing errors
- That meant `int53` errors never bubbled up properly to `rosbag.js`, and instead printed out silently to the console
- By updating `int53`, we ensure that errors are actually thrown to be caught by `rosbag.js`
- This PR also adds a try/catch to handle possible errors being thrown by `int53`

Bump version to 2.2.0: Update int53 package to properly bubble up errors to rosbag.js

---

src/parseMessageDefinition.js
src/parseMessageDefinition.test.js

This PR converts possible python bool values to a JSON compatible bool values. Check #56 
If not converted, parsing of these values fails for JSON.parse() function.
Fixes #56

add support for python bool values

---

babel.config.js
src/BagReader.js
src/BagReader.test.js
src/MessageReader.js
src/MessageReader.test.js
src/ReadResult.js
src/TimeUtil.js
src/TimeUtil.test.js
src/bag.js
src/bag.test.js
src/fields.js
src/fields.test.js
src/header.js
src/index.js
src/nmerge.js
src/node/index.js
src/node/index.test.js
src/parseMessageDefinition.js
src/parseMessageDefinition.test.js
src/record.js
src/types.js
src/web/index.js
src/web/index.test.js
webpack.config.js

Cruise's corporate entity is now Cruise LLC and not GM Cruise LLC, so we are updating all the license headers to the appropriate name.

Update header from GM Cruise LLC to Cruise LLC

---

README.md

With the current example in the readme you get a syntax error in Node.js
```
const bag = await open('../path/to/ros.bag');
^^^^^
SyntaxError: await is only valid in async function
at new Script (vm.js:80:7)
at createScript (vm.js:274:10)
at Object.runInThisContext (vm.js:326:10)
at Module._compile (internal/modules/cjs/loader.js:664:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
at startup (internal/bootstrap/node.js:283:19)
```
Edited it so that you don't get the syntax error

Update Readme with correct example

---

README.md
src/MessageReader.js
src/MessageReader.test.js
src/ReadResult.js
src/bag.js
src/bag.test.js

This way we can prevent our code or libraries from mutating raw
messages.
Initially I tried to do this on existing messages using the
`simple-deep-freeze` library, but that only works on “simple” objects
(without a custom prototype), but we want to keep custom prototypes
since they look better in the browser console, and they are necessary if
in the future we build lazy parsing. So just freezing them within
rosbag.js is better since that way we have more control over exactly how
the freezing works.
Test plan: added a bunch of tests.

Add “freeze” option for building immutable messages

---

src/bag.test.js

I thought that this was broken in rosbag.js, but it turns out it was
working fine all along! You do get the messages in the same order as
they appear in the bag, but that seems fine.

Add test for reading from shuffled bags

---

package.json
src/node/index.js
src/node/index.test.js
src/web/index.js
src/web/index.test.js

I clearly wasn’t careful enough in PR #64. This should properly expose
these methods.

Actually expose the fields methods as a public API

---

package.json
src/MessageReader.js

Instead of inlining every field for every submessage recursively, we
should instead use functions for distinct message types.
For types like
A { B b1, b2 };
B { C c1, c2 };
...
N { int dummy };
the size of the generated code is O(N) rather than O(2^N), and the size
of the largest function body is O(1) instead of O(2^N). This can make a
large performance difference for very large message definition DAGs in
Chrome (which will not optimise functions with code size larger than
128KB.) This results in a measured playback speedup of about 5% for
some bags in webviz.
(One possible downside, the maximum stack depth is now linear, not
constant. Probably not an issue in practice?)
The total number of function calls is not increased by this change, and
the the removal of the `this.field_X = …

Do not inline everything in generated parse code

---

package.json
src/MessageReader.js
src/MessageReader.test.js
src/parseMessageDefinition.js

-  Use `#pragma rosbag_parse_json` comment as a flag for when a specific ROS message field should be parsed into JSON

Use #pragma comment to specify when incoming ROS message field should be parsed as JSON

---

babel.config.js
package.json
yarn.lock

Fix for this issue when running `npm publish`:
Didn't update patch number in the package's version number, since previous commit was not successfully published to npm registry.

Add babel plugin to avoid syntax error when pushing to npm registry [EP-0]

---

HISTORY.md
package.json
src/MessageReader.js
src/MessageReader.test.js
src/MessageWriter.js
src/MessageWriter.test.js
src/bag.js
src/index.js

Add a message writer API that allows writing a message from a JS
object to ROS binary. This does not currently allow bag writing, and
I don't currently have plans to build or use that feature, so this
is mostly standalone for writing individual messages. It is mostly
translated from the existing MessageReader class.
Before writing the message we need to know the binary length of the
message, so we can create the buffer with that size. This currently
requires traversing the message twice, which is likely not very
efficient. I'm going to start with this approach and measure how
performant I need to make this before making further improvements.
Test plan: included all relevant tests from the MessageReader, just
converted to test writing instead.

Add message writer API

---

package.json
src/MessageReader.js
src/MessageReader.test.js

Presumably not caught by flow because we didn't want to put the
string alternative in the method signature.
Test plan: added a unit test.

Fix crash bug on deprecated input type

---

src/MessageWriter.js
src/node/index.js
src/web/index.js

In this PR I'm adding MessageWriter to the exported entities so we can use it in external projects.
In addition, I'm using `Buffer.allocUnsafe` instead of `new Buffer` as suggested by @MatthewSteel to prevent warnings.
Testing: all existing tests must pass

Export MessageWriter

---

package.json
src/MessageReader.js
src/MessageReader.test.js

This should take the same runtime but should reduce memory pressure
and garbage collection when reading ROS strings by not doing string
concatenation on every character.
Test plan: added test for long strings

More efficient parsing of message strings

---

package.json
src/MessageReader.js
src/MessageWriter.js
src/parseMessageDefinition.js
src/types.js

These types are used in Webviz and are important now that MessageReader
does not call parseMessageDefinitions directly.

Export message definition types

---

package.json
src/types.js

This union type adds complexity and isn't necessary. Also add the
value, which is parsed for constants but doesn't appear in the
type defintion. This will allow us to match the typedef in Webviz.
Test plan: only flow type change

Improve RosMsgField typedef

---

src/fields.js

Pass number instead of string into Buffer.indexOf

---

package.json
src/MessageReader.js

Prevent errors when called with a TypedArray backed by a SharedArrayBuffer
As a workaround, we can copy the requested info into another buffer, which should still be faster than manually converting one character at a time.

Prevent errors from SharedArrayBuffers

---

package.json
src/BagReader.js
src/MessageReader.js
src/MessageReader.test.js
src/MessageWriter.js
src/MessageWriter.test.js
src/bag.js
src/header.js
src/parseMessageDefinition.js
src/parseMessageDefinition.test.js
src/record.js
src/types.js

The algorithm for resolving ROS type names inside message definitions
that don't have a package specified is,
- If it's a primitive, use the primitive value.
- If it's the (reserved) type name `Header`, it's `std_msgs/Header`.
- Otherwise, use the package of the containing message.
(Note _containing_ message, not top-level message.)
This unfortunately necessitates a breaking change in API. Message
definitions can't be unambiguously parsed without knowing the package of
the top-level message. (Definition MD5s are similarly ambiguous.)
This felt like a good time to merge the named/unnamed definition types.
Test plan:
- Unit tests have been updated to use the new API.
- Tested against a development version of webviz. Works on a bag I
checked, and fixes the "ambiguous datatype" issue reported …

Add support for "ambiguous" type names

---

CONTRIBUTING.md
HISTORY.md
package.json
src/bag.ts
src/index.test.ts
src/index.ts
src/node/index.ts
src/web/index.ts

Also:
* Add release steps
* Release as v4.0.1

Add explicit exports so that types match code
